services:
  influxdb:
    image: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb2
    network_mode: host
    env_file:
      - ./.env
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./.env
    network_mode: host
  ampcons-api:
    build: ./ampcons-backend
    network_mode: host
    env_file:
      - ./.env
volumes:
  influxdb_data: {}
  grafana_data: {}
