openapi: 3.0.3
info:
  title: Ampcons
  version: 0.0.1

externalDocs:
  description: Github
  url: https://github.com/MatheusTomazella/ampcons-service

tags:
  - name: Measurements
    description: Read and write measurements of a component

paths:
  /measurement:
    post:
      tags:
        - Measurements
      summary: Insert a new measurement in the database for a component.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RawMeasurement'
        required: true
      responses:
        '200':
          description: Data inserted in the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement'
        '400':
          description: The body is missing a required field.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_MissingInformation'

components:
  schemas:
    RawMeasurement:
      type: object
      properties:
        tension: 
          type: integer
          description: Tension in volts (V)
          example: 127
        current: 
          type: number
          description: Current in amperes (A)
          example: 2.6
        comp_id:
          type: string
          description: Component uuid
          example: u4g67fvyitg346c7fyj34gf7
    Measurement:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        tension: 
          type: integer
          description: Tension in volts (V)
          example: 127
        current: 
          type: number
          description: Current in amperes (A)
          example: 2.6
        power:
          type: number
          description: Power in watts (W)
          example: 330.2
        comp_id:
          type: string
          description: Component uuid
          example: u4g67fvyitg346c7fyj34gf7

    Error_MissingInformation:
        type: object
        properties:
          missing_field:
            type: string
            example: comp_id